name: teleprospection_app
description: App mobile prospecteurs (MVP scaffold)
publish_to: 'none'
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  url_launcher: ^6.1.0

flutter:
  uses-material-design: true